/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

/**
 *
 * @author chris
 */
public class VentanaInicial extends javax.swing.JFrame {

    /**
     * Creates new form VentanaInicial
     */
    private String usuario1;
    private String usuario2;
    public VentanaInicial() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        label2 = new java.awt.Label();
        label1 = new java.awt.Label();
        txtNombreUsuario1 = new java.awt.TextField();
        txtNombreUsuario2 = new java.awt.TextField();
        label3 = new java.awt.Label();
        btnGuardar = new java.awt.Button();
        jLabel1 = new javax.swing.JLabel();
        btnComenzarJuego = new java.awt.Button();
        lbMostrarFichaB = new java.awt.Label();
        lbMostrarFichaA = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        label2.setText("Escriba el nombre del primer usuario:");
        jPanel1.add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 55, -1, -1));

        label1.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        label1.setText("Tres en Raya");
        jPanel1.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 153, -1));

        txtNombreUsuario1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel1.add(txtNombreUsuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 55, 193, -1));

        txtNombreUsuario2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel1.add(txtNombreUsuario2, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 91, 193, -1));

        label3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        label3.setText("Escriba el nombre del segundo usuario:");
        jPanel1.add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 91, -1, -1));

        btnGuardar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnGuardar.setLabel("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 127, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/portada.gif"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(417, 230, -1, -1));

        btnComenzarJuego.setEnabled(false);
        btnComenzarJuego.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnComenzarJuego.setLabel("Comenzar Juego");
        btnComenzarJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComenzarJuegoActionPerformed(evt);
            }
        });
        jPanel1.add(btnComenzarJuego, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        lbMostrarFichaB.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel1.add(lbMostrarFichaB, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 207, 300, -1));

        lbMostrarFichaA.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel1.add(lbMostrarFichaA, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 176, 300, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        usuario1=this.txtNombreUsuario1.getText();
        usuario2=this.txtNombreUsuario2.getText();
        btnGuardar.setVisible(false);
        
        lbMostrarFichaA.setText(usuario1+ " jugará primero, su ficha es: X");
        lbMostrarFichaB.setText(usuario2+ " jugará primero, su ficha es: O");
        btnComenzarJuego.setEnabled(true);
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnComenzarJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComenzarJuegoActionPerformed
       VentanaPrincipal nuevaVentanaP = new VentanaPrincipal(usuario1,usuario2);
       nuevaVentanaP.setVisible(true);
       dispose();
    }//GEN-LAST:event_btnComenzarJuegoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnComenzarJuego;
    private java.awt.Button btnGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label lbMostrarFichaA;
    private java.awt.Label lbMostrarFichaB;
    private java.awt.TextField txtNombreUsuario1;
    private java.awt.TextField txtNombreUsuario2;
    // End of variables declaration//GEN-END:variables
}
